import { EmojiCategory } from './chat.enum';
import { Emoji } from './chat.interface';

export const EMOJIS: Emoji[] = [
  {
    no: 1,
    title: 'face with tears of joy',
    category: EmojiCategory.Favorites,
    pic: '😂',
  },
  {
    no: 2,
    title: 'smiling face with heart-eyes',
    category: EmojiCategory.Favorites,
    pic: '😍',
  },
  {
    no: 3,
    title: 'smiling face with smiling eyes',
    category: EmojiCategory.Favorites,
    pic: '😊',
  },
  {
    no: 4,
    title: 'confused face',
    category: EmojiCategory.Favorites,
    pic: '😕',
  },
  {
    no: 5,
    title: 'OK hand',
    category: EmojiCategory.Favorites,
    pic: '👌',
  },
  {
    no: 6,
    title: 'rocket',
    category: EmojiCategory.Favorites,
    pic: '🚀',
  },
  {
    no: 7,
    title: 'trophy',
    category: EmojiCategory.Favorites,
    pic: '🏆',
  },
  {
    no: 8,
    title: 'beer mug',
    category: EmojiCategory.Favorites,
    pic: '🍺',
  },
  {
    no: 9,
    title: 'red heart',
    category: EmojiCategory.Favorites,
    pic: '❤️',
  },
  {
    no: 10,
    title: 'grinning face with smiling eyes',
    category: EmojiCategory.People,
    pic: '😄',
  },
  {
    no: 11,
    title: 'grinning face with big eyes',
    category: EmojiCategory.People,
    pic: '😃',
  },
  {
    no: 12,
    title: 'grinning face',
    category: EmojiCategory.People,
    pic: '😀',
  },
  {
    no: 13,
    title: 'smiling face with smiling eyes',
    category: EmojiCategory.People,
    pic: '😊',
  },
  {
    no: 14,
    title: 'winking face',
    category: EmojiCategory.People,
    pic: '😉',
  },
  {
    no: 15,
    title: 'smiling face with heart-eyes',
    category: EmojiCategory.People,
    pic: '😍',
  },
  {
    no: 16,
    title: 'face blowing a kiss',
    category: EmojiCategory.People,
    pic: '😘',
  },
  {
    no: 17,
    title: 'kissing face with closed eyes',
    category: EmojiCategory.People,
    pic: '😚',
  },
  {
    no: 18,
    title: 'kissing face',
    category: EmojiCategory.People,
    pic: '😗',
  },
  {
    no: 19,
    title: 'kissing face with smiling eyes',
    category: EmojiCategory.People,
    pic: '😙',
  },
  {
    no: 20,
    title: 'winking face with tongue',
    category: EmojiCategory.People,
    pic: '😜',
  },
  {
    no: 21,
    title: 'squinting face with tongue',
    category: EmojiCategory.People,
    pic: '😝',
  },
  {
    no: 22,
    title: 'face with tongue',
    category: EmojiCategory.People,
    pic: '😛',
  },
  {
    no: 23,
    title: 'flushed face',
    category: EmojiCategory.People,
    pic: '😳',
  },
  {
    no: 24,
    title: 'beaming face with smiling eyes',
    category: EmojiCategory.People,
    pic: '😁',
  },
  {
    no: 25,
    title: 'pensive face',
    category: EmojiCategory.People,
    pic: '😔',
  },
  {
    no: 26,
    title: 'relieved face',
    category: EmojiCategory.People,
    pic: '😌',
  },
  {
    no: 27,
    title: 'unamused face',
    category: EmojiCategory.People,
    pic: '😒',
  },
  {
    no: 28,
    title: 'disappointed face',
    category: EmojiCategory.People,
    pic: '😞',
  },
  {
    no: 29,
    title: 'persevering face',
    category: EmojiCategory.People,
    pic: '😣',
  },
  {
    no: 30,
    title: 'crying face',
    category: EmojiCategory.People,
    pic: '😢',
  },
  {
    no: 31,
    title: 'face with tears of joy',
    category: EmojiCategory.People,
    pic: '😂',
  },
  {
    no: 32,
    title: 'loudly crying face',
    category: EmojiCategory.People,
    pic: '😭',
  },
  {
    no: 33,
    title: 'sleepy face',
    category: EmojiCategory.People,
    pic: '😪',
  },
  {
    no: 34,
    title: 'sad but relieved face',
    category: EmojiCategory.People,
    pic: '😥',
  },
  {
    no: 35,
    title: 'anxious face with sweat',
    category: EmojiCategory.People,
    pic: '😰',
  },
  {
    no: 36,
    title: 'grinning face with sweat',
    category: EmojiCategory.People,
    pic: '😅',
  },
  {
    no: 37,
    title: 'downcast face with sweat',
    category: EmojiCategory.People,
    pic: '😓',
  },
  {
    no: 38,
    title: 'weary face',
    category: EmojiCategory.People,
    pic: '😩',
  },
  {
    no: 39,
    title: 'tired face',
    category: EmojiCategory.People,
    pic: '😫',
  },
  {
    no: 40,
    title: 'fearful face',
    category: EmojiCategory.People,
    pic: '😨',
  },
  {
    no: 41,
    title: 'face screaming in fear',
    category: EmojiCategory.People,
    pic: '😱',
  },
  {
    no: 42,
    title: 'angry face',
    category: EmojiCategory.People,
    pic: '😠',
  },
  {
    no: 43,
    title: 'pouting face',
    category: EmojiCategory.People,
    pic: '😡',
  },
  {
    no: 44,
    title: 'face with steam from nose',
    category: EmojiCategory.People,
    pic: '😤',
  },
  {
    no: 45,
    title: 'confounded face',
    category: EmojiCategory.People,
    pic: '😖',
  },
  {
    no: 46,
    title: 'grinning squinting face',
    category: EmojiCategory.People,
    pic: '😆',
  },
  {
    no: 47,
    title: 'face savoring food',
    category: EmojiCategory.People,
    pic: '😋',
  },
  {
    no: 48,
    title: 'face with medical mask',
    category: EmojiCategory.People,
    pic: '😷',
  },
  {
    no: 49,
    title: 'smiling face with sunglasses',
    category: EmojiCategory.People,
    pic: '😎',
  },
  {
    no: 50,
    title: 'sleeping face',
    category: EmojiCategory.People,
    pic: '😴',
  },
  {
    no: 51,
    title: 'dizzy face',
    category: EmojiCategory.People,
    pic: '😵',
  },
  {
    no: 52,
    title: 'astonished face',
    category: EmojiCategory.People,
    pic: '😲',
  },
  {
    no: 53,
    title: 'worried face',
    category: EmojiCategory.People,
    pic: '😟',
  },
  {
    no: 54,
    title: 'frowning face with open mouth',
    category: EmojiCategory.People,
    pic: '😦',
  },
  {
    no: 55,
    title: 'anguished face',
    category: EmojiCategory.People,
    pic: '😧',
  },
  {
    no: 56,
    title: 'angry face with horns',
    category: EmojiCategory.People,
    pic: '👿',
  },
  {
    no: 57,
    title: 'face with open mouth',
    category: EmojiCategory.People,
    pic: '😮',
  },
  {
    no: 58,
    title: 'grimacing face',
    category: EmojiCategory.People,
    pic: '😬',
  },
  {
    no: 59,
    title: 'neutral face',
    category: EmojiCategory.People,
    pic: '😐',
  },
  {
    no: 60,
    title: 'confused face',
    category: EmojiCategory.People,
    pic: '😕',
  },
  {
    no: 61,
    title: 'hushed face',
    category: EmojiCategory.People,
    pic: '😯',
  },
  {
    no: 62,
    title: 'smirking face',
    category: EmojiCategory.People,
    pic: '😏',
  },
  {
    no: 63,
    title: 'expressionless face',
    category: EmojiCategory.People,
    pic: '😑',
  },
  {
    no: 64,
    title: 'slightly frowning face',
    category: EmojiCategory.People,
    pic: '🙁',
  },
  {
    no: 65,
    title: 'face with rolling eyes',
    category: EmojiCategory.People,
    pic: '🙄',
  },
  {
    no: 66,
    title: 'thinking face',
    category: EmojiCategory.People,
    pic: '🤔',
  },
  {
    no: 67,
    title: 'zipper-mouth face',
    category: EmojiCategory.People,
    pic: '🤐',
  },
  {
    no: 68,
    title: 'face with thermometer',
    category: EmojiCategory.People,
    pic: '🤒',
  },
  {
    no: 69,
    title: 'face with head-bandage',
    category: EmojiCategory.People,
    pic: '🤕',
  },
  {
    no: 70,
    title: 'slightly smiling face',
    category: EmojiCategory.People,
    pic: '🙂',
  },
  {
    no: 71,
    title: 'upside-down face',
    category: EmojiCategory.People,
    pic: '🙃',
  },
  {
    no: 72,
    title: 'money-mouth face',
    category: EmojiCategory.People,
    pic: '🤑',
  },
  {
    no: 73,
    title: 'hugging face',
    category: EmojiCategory.People,
    pic: '🤗',
  },
  {
    no: 74,
    title: 'nerd face',
    category: EmojiCategory.People,
    pic: '🤓',
  },
  {
    no: 75,
    title: 'princess',
    category: EmojiCategory.People,
    pic: '👸',
  },
  {
    no: 76,
    title: 'ogre',
    category: EmojiCategory.People,
    pic: '👹',
  },
  {
    no: 77,
    title: 'goblin',
    category: EmojiCategory.People,
    pic: '👺',
  },
  {
    no: 78,
    title: 'see-no-evil monkey',
    category: EmojiCategory.People,
    pic: '🙈',
  },
  {
    no: 79,
    title: 'hear-no-evil monkey',
    category: EmojiCategory.People,
    pic: '🙉',
  },
  {
    no: 80,
    title: 'speak-no-evil monkey',
    category: EmojiCategory.People,
    pic: '🙊',
  },
  {
    no: 81,
    title: 'skull',
    category: EmojiCategory.People,
    pic: '💀',
  },
  {
    no: 82,
    title: 'alien',
    category: EmojiCategory.People,
    pic: '👽',
  },
  {
    no: 83,
    title: 'pile of poo',
    category: EmojiCategory.People,
    pic: '💩',
  },
  {
    no: 84,
    title: 'fire',
    category: EmojiCategory.People,
    pic: '🔥',
  },
  {
    no: 85,
    title: 'sparkles',
    category: EmojiCategory.People,
    pic: '✨',
  },
  {
    no: 86,
    title: 'glowing star',
    category: EmojiCategory.People,
    pic: '🌟',
  },
  {
    no: 87,
    title: 'collision',
    category: EmojiCategory.People,
    pic: '💥',
  },
  {
    no: 88,
    title: 'sweat droplets',
    category: EmojiCategory.People,
    pic: '💦',
  },
  {
    no: 89,
    title: 'droplet',
    category: EmojiCategory.People,
    pic: '💧',
  },
  {
    no: 90,
    title: 'zzz',
    category: EmojiCategory.People,
    pic: '💤',
  },
  {
    no: 91,
    title: 'dashing away',
    category: EmojiCategory.People,
    pic: '💨',
  },
  {
    no: 92,
    title: 'ear',
    category: EmojiCategory.People,
    pic: '👂',
  },
  {
    no: 93,
    title: 'eyes',
    category: EmojiCategory.People,
    pic: '👀',
  },
  {
    no: 94,
    title: 'nose',
    category: EmojiCategory.People,
    pic: '👃',
  },
  {
    no: 95,
    title: 'tongue',
    category: EmojiCategory.People,
    pic: '👅',
  },
  {
    no: 96,
    title: 'mouth',
    category: EmojiCategory.People,
    pic: '👄',
  },
  {
    no: 97,
    title: 'thumbs up',
    category: EmojiCategory.People,
    pic: '👍',
  },
  {
    no: 98,
    title: 'thumbs down',
    category: EmojiCategory.People,
    pic: '👎',
  },
  {
    no: 99,
    title: 'OK hand',
    category: EmojiCategory.People,
    pic: '👌',
  },
  {
    no: 100,
    title: 'oncoming fist',
    category: EmojiCategory.People,
    pic: '👊',
  },
  {
    no: 101,
    title: 'raised fist',
    category: EmojiCategory.People,
    pic: '✊',
  },
  {
    no: 102,
    title: 'waving hand',
    category: EmojiCategory.People,
    pic: '👋',
  },
  {
    no: 103,
    title: 'raised hand',
    category: EmojiCategory.People,
    pic: '✋',
  },
  {
    no: 104,
    title: 'open hands',
    category: EmojiCategory.People,
    pic: '👐',
  },
  {
    no: 105,
    title: 'backhand index pointing up',
    category: EmojiCategory.People,
    pic: '👆',
  },
  {
    no: 106,
    title: 'backhand index pointing down',
    category: EmojiCategory.People,
    pic: '👇',
  },
  {
    no: 107,
    title: 'backhand index pointing right',
    category: EmojiCategory.People,
    pic: '👉',
  },
  {
    no: 108,
    title: 'backhand index pointing left',
    category: EmojiCategory.People,
    pic: '👈',
  },
  {
    no: 109,
    title: 'sign of the horns',
    category: EmojiCategory.People,
    pic: '🤘',
  },
  {
    no: 110,
    title: 'hand with fingers splayed',
    category: EmojiCategory.People,
    pic: '🖐',
  },
  {
    no: 111,
    title: 'vulcan salute',
    category: EmojiCategory.People,
    pic: '🖖',
  },
  {
    no: 112,
    title: 'middle finger',
    category: EmojiCategory.People,
    pic: '🖕',
  },
  {
    no: 113,
    title: 'raising hands',
    category: EmojiCategory.People,
    pic: '🙌',
  },
  {
    no: 114,
    title: 'folded hands',
    category: EmojiCategory.People,
    pic: '🙏',
  },
  {
    no: 115,
    title: 'clapping hands',
    category: EmojiCategory.People,
    pic: '👏',
  },
  {
    no: 116,
    title: 'flexed biceps',
    category: EmojiCategory.People,
    pic: '💪',
  },
  {
    no: 117,
    title: 'woman dancing',
    category: EmojiCategory.People,
    pic: '💃',
  },
  {
    no: 118,
    title: 'woman and man holding hands',
    category: EmojiCategory.People,
    pic: '👫',
  },
  {
    no: 119,
    title: 'family',
    category: EmojiCategory.People,
    pic: '👪',
  },
  {
    no: 120,
    title: 'kiss',
    category: EmojiCategory.People,
    pic: '💏',
  },
  {
    no: 121,
    title: 'person gesturing OK',
    category: EmojiCategory.People,
    pic: '🙆',
  },
  {
    no: 122,
    title: 'person gesturing NO',
    category: EmojiCategory.People,
    pic: '🙅',
  },
  {
    no: 123,
    title: 'person tipping hand',
    category: EmojiCategory.People,
    pic: '💁',
  },
  {
    no: 124,
    title: 'person raising hand',
    category: EmojiCategory.People,
    pic: '🙋',
  },
  {
    no: 125,
    title: 'person getting massage',
    category: EmojiCategory.People,
    pic: '💆',
  },
  {
    no: 126,
    title: 'person getting haircut',
    category: EmojiCategory.People,
    pic: '💇',
  },
  {
    no: 127,
    title: 'nail polish',
    category: EmojiCategory.People,
    pic: '💅',
  },
  {
    no: 128,
    title: 'bride with veil',
    category: EmojiCategory.People,
    pic: '👰',
  },
  {
    no: 129,
    title: 'person pouting',
    category: EmojiCategory.People,
    pic: '🙎',
  },
  {
    no: 130,
    title: 'person frowning',
    category: EmojiCategory.People,
    pic: '🙍',
  },
  {
    no: 131,
    title: 'person bowing',
    category: EmojiCategory.People,
    pic: '🙇',
  },
  {
    no: 132,
    title: 'top hat',
    category: EmojiCategory.People,
    pic: '🎩',
  },
  {
    no: 133,
    title: 'crown',
    category: EmojiCategory.People,
    pic: '👑',
  },
  {
    no: 134,
    title: 'red heart',
    category: EmojiCategory.People,
    pic: '❤️',
  },
  {
    no: 135,
    title: 'yellow heart',
    category: EmojiCategory.People,
    pic: '💛',
  },
  {
    no: 136,
    title: 'blue heart',
    category: EmojiCategory.People,
    pic: '💙',
  },
  {
    no: 137,
    title: 'purple heart',
    category: EmojiCategory.People,
    pic: '💜',
  },
  {
    no: 138,
    title: 'green heart',
    category: EmojiCategory.People,
    pic: '💚',
  },
  {
    no: 139,
    title: 'broken heart',
    category: EmojiCategory.People,
    pic: '💔',
  },
  {
    no: 140,
    title: 'growing heart',
    category: EmojiCategory.People,
    pic: '💗',
  },
  {
    no: 141,
    title: 'beating heart',
    category: EmojiCategory.People,
    pic: '💓',
  },
  {
    no: 142,
    title: 'two hearts',
    category: EmojiCategory.People,
    pic: '💕',
  },
  {
    no: 143,
    title: 'sparkling heart',
    category: EmojiCategory.People,
    pic: '💖',
  },
  {
    no: 144,
    title: 'revolving hearts',
    category: EmojiCategory.People,
    pic: '💞',
  },
  {
    no: 145,
    title: 'heart with arrow',
    category: EmojiCategory.People,
    pic: '💘',
  },
  {
    no: 146,
    title: 'love letter',
    category: EmojiCategory.People,
    pic: '💌',
  },
  {
    no: 147,
    title: 'kiss mark',
    category: EmojiCategory.People,
    pic: '💋',
  },
  {
    no: 148,
    title: 'ring',
    category: EmojiCategory.People,
    pic: '💍',
  },
  {
    no: 149,
    title: 'gem stone',
    category: EmojiCategory.People,
    pic: '💎',
  },
  {
    no: 150,
    title: 'robot',
    category: EmojiCategory.People,
    pic: '🤖',
  },
  {
    no: 151,
    title: 'dog face',
    category: EmojiCategory.Nature,
    pic: '🐶',
  },
  {
    no: 152,
    title: 'wolf',
    category: EmojiCategory.Nature,
    pic: '🐺',
  },
  {
    no: 153,
    title: 'cat face',
    category: EmojiCategory.Nature,
    pic: '🐱',
  },
  {
    no: 154,
    title: 'mouse face',
    category: EmojiCategory.Nature,
    pic: '🐭',
  },
  {
    no: 155,
    title: 'hamster',
    category: EmojiCategory.Nature,
    pic: '🐹',
  },
  {
    no: 156,
    title: 'rabbit face',
    category: EmojiCategory.Nature,
    pic: '🐰',
  },
  {
    no: 157,
    title: 'frog',
    category: EmojiCategory.Nature,
    pic: '🐸',
  },
  {
    no: 158,
    title: 'tiger face',
    category: EmojiCategory.Nature,
    pic: '🐯',
  },
  {
    no: 159,
    title: 'koala',
    category: EmojiCategory.Nature,
    pic: '🐨',
  },
  {
    no: 160,
    title: 'bear',
    category: EmojiCategory.Nature,
    pic: '🐻',
  },
  {
    no: 161,
    title: 'pig face',
    category: EmojiCategory.Nature,
    pic: '🐷',
  },
  {
    no: 162,
    title: 'pig nose',
    category: EmojiCategory.Nature,
    pic: '🐽',
  },
  {
    no: 163,
    title: 'cow face',
    category: EmojiCategory.Nature,
    pic: '🐮',
  },
  {
    no: 164,
    title: 'boar',
    category: EmojiCategory.Nature,
    pic: '🐗',
  },
  {
    no: 165,
    title: 'monkey face',
    category: EmojiCategory.Nature,
    pic: '🐵',
  },
  {
    no: 166,
    title: 'monkey',
    category: EmojiCategory.Nature,
    pic: '🐒',
  },
  {
    no: 167,
    title: 'horse face',
    category: EmojiCategory.Nature,
    pic: '🐴',
  },
  {
    no: 168,
    title: 'ewe',
    category: EmojiCategory.Nature,
    pic: '🐑',
  },
  {
    no: 169,
    title: 'elephant',
    category: EmojiCategory.Nature,
    pic: '🐘',
  },
  {
    no: 170,
    title: 'panda',
    category: EmojiCategory.Nature,
    pic: '🐼',
  },
  {
    no: 171,
    title: 'penguin',
    category: EmojiCategory.Nature,
    pic: '🐧',
  },
  {
    no: 172,
    title: 'bird',
    category: EmojiCategory.Nature,
    pic: '🐦',
  },
  {
    no: 173,
    title: 'baby chick',
    category: EmojiCategory.Nature,
    pic: '🐤',
  },
  {
    no: 174,
    title: 'front-facing baby chick',
    category: EmojiCategory.Nature,
    pic: '🐥',
  },
  {
    no: 175,
    title: 'hatching chick',
    category: EmojiCategory.Nature,
    pic: '🐣',
  },
  {
    no: 176,
    title: 'chicken',
    category: EmojiCategory.Nature,
    pic: '🐔',
  },
  {
    no: 177,
    title: 'snake',
    category: EmojiCategory.Nature,
    pic: '🐍',
  },
  {
    no: 178,
    title: 'turtle',
    category: EmojiCategory.Nature,
    pic: '🐢',
  },
  {
    no: 179,
    title: 'bug',
    category: EmojiCategory.Nature,
    pic: '🐛',
  },
  {
    no: 180,
    title: 'honeybee',
    category: EmojiCategory.Nature,
    pic: '🐝',
  },
  {
    no: 181,
    title: 'ant',
    category: EmojiCategory.Nature,
    pic: '🐜',
  },
  {
    no: 182,
    title: 'lady beetle',
    category: EmojiCategory.Nature,
    pic: '🐞',
  },
  {
    no: 183,
    title: 'snail',
    category: EmojiCategory.Nature,
    pic: '🐌',
  },
  {
    no: 184,
    title: 'lion',
    category: EmojiCategory.Nature,
    pic: '🦁',
  },
  {
    no: 185,
    title: 'unicorn',
    category: EmojiCategory.Nature,
    pic: '🦄',
  },
  {
    no: 186,
    title: 'spider',
    category: EmojiCategory.Nature,
    pic: '🕷',
  },
  {
    no: 187,
    title: 'spider web',
    category: EmojiCategory.Nature,
    pic: '🕸',
  },
  {
    no: 188,
    title: 'scorpion',
    category: EmojiCategory.Nature,
    pic: '🦂',
  },
  {
    no: 189,
    title: 'crab',
    category: EmojiCategory.Nature,
    pic: '🦀',
  },
  {
    no: 190,
    title: 'turkey',
    category: EmojiCategory.Nature,
    pic: '🦃',
  },
  {
    no: 191,
    title: 'dove',
    category: EmojiCategory.Nature,
    pic: '🕊',
  },
  {
    no: 192,
    title: 'chipmunk',
    category: EmojiCategory.Nature,
    pic: '🐿',
  },
  {
    no: 193,
    title: 'octopus',
    category: EmojiCategory.Nature,
    pic: '🐙',
  },
  {
    no: 194,
    title: 'spiral shell',
    category: EmojiCategory.Nature,
    pic: '🐚',
  },
  {
    no: 195,
    title: 'tropical fish',
    category: EmojiCategory.Nature,
    pic: '🐠',
  },
  {
    no: 196,
    title: 'fish',
    category: EmojiCategory.Nature,
    pic: '🐟',
  },
  {
    no: 197,
    title: 'dolphin',
    category: EmojiCategory.Nature,
    pic: '🐬',
  },
  {
    no: 198,
    title: 'spouting whale',
    category: EmojiCategory.Nature,
    pic: '🐳',
  },
  {
    no: 199,
    title: 'horse',
    category: EmojiCategory.Nature,
    pic: '🐎',
  },
  {
    no: 200,
    title: 'dragon face',
    category: EmojiCategory.Nature,
    pic: '🐲',
  },
  {
    no: 201,
    title: 'blowfish',
    category: EmojiCategory.Nature,
    pic: '🐡',
  },
  {
    no: 202,
    title: 'two-hump camel',
    category: EmojiCategory.Nature,
    pic: '🐫',
  },
  {
    no: 203,
    title: 'poodle',
    category: EmojiCategory.Nature,
    pic: '🐩',
  },
  {
    no: 204,
    title: 'bouquet',
    category: EmojiCategory.Nature,
    pic: '💐',
  },
  {
    no: 205,
    title: 'rose',
    category: EmojiCategory.Nature,
    pic: '🌹',
  },
  {
    no: 206,
    title: 'sunflower',
    category: EmojiCategory.Nature,
    pic: '🌻',
  },
  {
    no: 207,
    title: 'mushroom',
    category: EmojiCategory.Nature,
    pic: '🍄',
  },
  {
    no: 208,
    title: 'cactus',
    category: EmojiCategory.Nature,
    pic: '🌵',
  },
  {
    no: 209,
    title: 'new moon',
    category: EmojiCategory.Nature,
    pic: '🌑',
  },
  {
    no: 210,
    title: 'first quarter moon',
    category: EmojiCategory.Nature,
    pic: '🌓',
  },
  {
    no: 211,
    title: 'waxing gibbous moon',
    category: EmojiCategory.Nature,
    pic: '🌔',
  },
  {
    no: 212,
    title: 'full moon',
    category: EmojiCategory.Nature,
    pic: '🌕',
  },
  {
    no: 213,
    title: 'first quarter moon face',
    category: EmojiCategory.Nature,
    pic: '🌛',
  },
  {
    no: 214,
    title: 'crescent moon',
    category: EmojiCategory.Nature,
    pic: '🌙',
  },
  {
    no: 215,
    title: 'globe showing Asia-Australia',
    category: EmojiCategory.Nature,
    pic: '🌏',
  },
  {
    no: 216,
    title: 'sun behind cloud',
    category: EmojiCategory.Nature,
    pic: '⛅',
  },
  {
    no: 217,
    title: 'snowman without snow',
    category: EmojiCategory.Nature,
    pic: '⛄',
  },
  {
    no: 218,
    title: 'water wave',
    category: EmojiCategory.Nature,
    pic: '🌊',
  },
  {
    no: 219,
    title: 'sun behind small cloud',
    category: EmojiCategory.Nature,
    pic: '🌤',
  },
  {
    no: 220,
    title: 'sun behind large cloud',
    category: EmojiCategory.Nature,
    pic: '🌥',
  },
  {
    no: 221,
    title: 'sun behind rain cloud',
    category: EmojiCategory.Nature,
    pic: '🌦',
  },
  {
    no: 222,
    title: 'cloud with rain',
    category: EmojiCategory.Nature,
    pic: '🌧',
  },
  {
    no: 223,
    title: 'cloud with lightning',
    category: EmojiCategory.Nature,
    pic: '🌩',
  },
  {
    no: 224,
    title: 'cloud with snow',
    category: EmojiCategory.Nature,
    pic: '🌨',
  },
  {
    no: 225,
    title: 'wind face',
    category: EmojiCategory.Nature,
    pic: '🌬',
  },
  {
    no: 226,
    title: 'tornado',
    category: EmojiCategory.Nature,
    pic: '🌪',
  },
  {
    no: 227,
    title: 'graduation cap',
    category: EmojiCategory.Objects,
    pic: '🎓',
  },
  {
    no: 228,
    title: 'fireworks',
    category: EmojiCategory.Objects,
    pic: '🎆',
  },
  {
    no: 229,
    title: 'sparkler',
    category: EmojiCategory.Objects,
    pic: '🎇',
  },
  {
    no: 230,
    title: 'jack-o-lantern',
    category: EmojiCategory.Objects,
    pic: '🎃',
  },
  {
    no: 231,
    title: 'ghost',
    category: EmojiCategory.Objects,
    pic: '👻',
  },
  {
    no: 232,
    title: 'Santa Claus',
    category: EmojiCategory.Objects,
    pic: '🎅',
  },
  {
    no: 233,
    title: 'Christmas tree',
    category: EmojiCategory.Objects,
    pic: '🎄',
  },
  {
    no: 234,
    title: 'wrapped gift',
    category: EmojiCategory.Objects,
    pic: '🎁',
  },
  {
    no: 235,
    title: 'party popper',
    category: EmojiCategory.Objects,
    pic: '🎉',
  },
  {
    no: 236,
    title: 'confetti ball',
    category: EmojiCategory.Objects,
    pic: '🎊',
  },
  {
    no: 237,
    title: 'balloon',
    category: EmojiCategory.Objects,
    pic: '🎈',
  },
  {
    no: 238,
    title: 'light bulb',
    category: EmojiCategory.Objects,
    pic: '💡',
  },
  {
    no: 239,
    title: 'toilet',
    category: EmojiCategory.Objects,
    pic: '🚽',
  },
  {
    no: 240,
    title: 'wrench',
    category: EmojiCategory.Objects,
    pic: '🔧',
  },
  {
    no: 241,
    title: 'nut and bolt',
    category: EmojiCategory.Objects,
    pic: '🔩',
  },
  {
    no: 242,
    title: 'hammer',
    category: EmojiCategory.Objects,
    pic: '🔨',
  },
  {
    no: 243,
    title: 'cigarette',
    category: EmojiCategory.Objects,
    pic: '🚬',
  },
  {
    no: 244,
    title: 'bomb',
    category: EmojiCategory.Objects,
    pic: '💣',
  },
  {
    no: 245,
    title: 'pistol',
    category: EmojiCategory.Objects,
    pic: '🔫',
  },
  {
    no: 246,
    title: 'kitchen knife',
    category: EmojiCategory.Objects,
    pic: '🔪',
  },
  {
    no: 247,
    title: 'pill',
    category: EmojiCategory.Objects,
    pic: '💊',
  },
  {
    no: 248,
    title: 'syringe',
    category: EmojiCategory.Objects,
    pic: '💉',
  },
  {
    no: 249,
    title: 'money bag',
    category: EmojiCategory.Objects,
    pic: '💰',
  },
  {
    no: 250,
    title: 'yen banknote',
    category: EmojiCategory.Objects,
    pic: '💴',
  },
  {
    no: 251,
    title: 'dollar banknote',
    category: EmojiCategory.Objects,
    pic: '💵',
  },
  {
    no: 252,
    title: 'credit card',
    category: EmojiCategory.Objects,
    pic: '💳',
  },
  {
    no: 253,
    title: 'money with wings',
    category: EmojiCategory.Objects,
    pic: '💸',
  },
  {
    no: 254,
    title: 'clapper board',
    category: EmojiCategory.Objects,
    pic: '🎬',
  },
  {
    no: 255,
    title: 'microphone',
    category: EmojiCategory.Objects,
    pic: '🎤',
  },
  {
    no: 256,
    title: 'alien monster',
    category: EmojiCategory.Objects,
    pic: '👾',
  },
  {
    no: 257,
    title: 'video game',
    category: EmojiCategory.Objects,
    pic: '🎮',
  },
  {
    no: 258,
    title: 'joker',
    category: EmojiCategory.Objects,
    pic: '🃏',
  },
  {
    no: 259,
    title: 'mahjong red dragon',
    category: EmojiCategory.Objects,
    pic: '🀄',
  },
  {
    no: 260,
    title: 'game die',
    category: EmojiCategory.Objects,
    pic: '🎲',
  },
  {
    no: 261,
    title: 'direct hit',
    category: EmojiCategory.Objects,
    pic: '🎯',
  },
  {
    no: 262,
    title: 'pool 8 ball',
    category: EmojiCategory.Objects,
    pic: '🎱',
  },
  {
    no: 263,
    title: 'chequered flag',
    category: EmojiCategory.Objects,
    pic: '🏁',
  },
  {
    no: 264,
    title: 'trophy',
    category: EmojiCategory.Objects,
    pic: '🏆',
  },
  {
    no: 265,
    title: 'beer mug',
    category: EmojiCategory.Objects,
    pic: '🍺',
  },
  {
    no: 266,
    title: 'cocktail glass',
    category: EmojiCategory.Objects,
    pic: '🍸',
  },
  {
    no: 267,
    title: 'tropical drink',
    category: EmojiCategory.Objects,
    pic: '🍹',
  },
  {
    no: 268,
    title: 'wine glass',
    category: EmojiCategory.Objects,
    pic: '🍷',
  },
  {
    no: 269,
    title: 'fork and knife',
    category: EmojiCategory.Objects,
    pic: '🍴',
  },
  {
    no: 270,
    title: 'pizza',
    category: EmojiCategory.Objects,
    pic: '🍕',
  },
  {
    no: 271,
    title: 'hamburger',
    category: EmojiCategory.Objects,
    pic: '🍔',
  },
  {
    no: 272,
    title: 'french fries',
    category: EmojiCategory.Objects,
    pic: '🍟',
  },
  {
    no: 273,
    title: 'poultry leg',
    category: EmojiCategory.Objects,
    pic: '🍗',
  },
  {
    no: 274,
    title: 'spaghetti',
    category: EmojiCategory.Objects,
    pic: '🍝',
  },
  {
    no: 275,
    title: 'bento box',
    category: EmojiCategory.Objects,
    pic: '🍱',
  },
  {
    no: 276,
    title: 'steaming bowl',
    category: EmojiCategory.Objects,
    pic: '🍜',
  },
  {
    no: 277,
    title: 'cooking',
    category: EmojiCategory.Objects,
    pic: '🍳',
  },
  {
    no: 278,
    title: 'bread',
    category: EmojiCategory.Objects,
    pic: '🍞',
  },
  {
    no: 279,
    title: 'doughnut',
    category: EmojiCategory.Objects,
    pic: '🍩',
  },
  {
    no: 280,
    title: 'soft ice cream',
    category: EmojiCategory.Objects,
    pic: '🍦',
  },
  {
    no: 281,
    title: 'birthday cake',
    category: EmojiCategory.Objects,
    pic: '🎂',
  },
  {
    no: 282,
    title: 'shortcake',
    category: EmojiCategory.Objects,
    pic: '🍰',
  },
  {
    no: 283,
    title: 'cookie',
    category: EmojiCategory.Objects,
    pic: '🍪',
  },
  {
    no: 284,
    title: 'chocolate bar',
    category: EmojiCategory.Objects,
    pic: '🍫',
  },
  {
    no: 285,
    title: 'lollipop',
    category: EmojiCategory.Objects,
    pic: '🍭',
  },
  {
    no: 286,
    title: 'honey pot',
    category: EmojiCategory.Objects,
    pic: '🍯',
  },
  {
    no: 287,
    title: 'red apple',
    category: EmojiCategory.Objects,
    pic: '🍎',
  },
  {
    no: 288,
    title: 'cherries',
    category: EmojiCategory.Objects,
    pic: '🍒',
  },
  {
    no: 289,
    title: 'strawberry',
    category: EmojiCategory.Objects,
    pic: '🍓',
  },
  {
    no: 290,
    title: 'peach',
    category: EmojiCategory.Objects,
    pic: '🍑',
  },
  {
    no: 291,
    title: 'banana',
    category: EmojiCategory.Objects,
    pic: '🍌',
  },
  {
    no: 292,
    title: 'pineapple',
    category: EmojiCategory.Objects,
    pic: '🍍',
  },
  {
    no: 293,
    title: 'eggplant',
    category: EmojiCategory.Objects,
    pic: '🍆',
  },
  {
    no: 294,
    title: 'tomato',
    category: EmojiCategory.Objects,
    pic: '🍅',
  },
  {
    no: 295,
    title: 'ear of corn',
    category: EmojiCategory.Objects,
    pic: '🌽',
  },
  {
    no: 296,
    title: 'hot pepper',
    category: EmojiCategory.Objects,
    pic: '🌶',
  },
  {
    no: 297,
    title: 'cheese wedge',
    category: EmojiCategory.Objects,
    pic: '🧀',
  },
  {
    no: 298,
    title: 'hot dog',
    category: EmojiCategory.Objects,
    pic: '🌭',
  },
  {
    no: 299,
    title: 'taco',
    category: EmojiCategory.Objects,
    pic: '🌮',
  },
  {
    no: 300,
    title: 'burrito',
    category: EmojiCategory.Objects,
    pic: '🌯',
  },
  {
    no: 301,
    title: 'popcorn',
    category: EmojiCategory.Objects,
    pic: '🍿',
  },
  {
    no: 302,
    title: 'bottle with popping cork',
    category: EmojiCategory.Objects,
    pic: '🍾',
  },
  {
    no: 303,
    title: 'fork and knife with plate',
    category: EmojiCategory.Objects,
    pic: '🍽',
  },
  {
    no: 304,
    title: 'ping pong',
    category: EmojiCategory.Objects,
    pic: '🏓',
  },
  {
    no: 305,
    title: 'sports medal',
    category: EmojiCategory.Objects,
    pic: '🏅',
  },
  {
    no: 306,
    title: 'military medal',
    category: EmojiCategory.Objects,
    pic: '🎖',
  },
  {
    no: 307,
    title: 'joystick',
    category: EmojiCategory.Objects,
    pic: '🕹',
  },
  {
    no: 308,
    title: 'hammer and wrench',
    category: EmojiCategory.Objects,
    pic: '🛠',
  },
  {
    no: 309,
    title: 'dagger',
    category: EmojiCategory.Objects,
    pic: '🗡',
  },
  {
    no: 310,
    title: 'speedboat',
    category: EmojiCategory.Places,
    pic: '🚤',
  },
  {
    no: 311,
    title: 'rocket',
    category: EmojiCategory.Places,
    pic: '🚀',
  },
  {
    no: 312,
    title: 'high-speed train',
    category: EmojiCategory.Places,
    pic: '🚄',
  },
  {
    no: 313,
    title: 'bullet train',
    category: EmojiCategory.Places,
    pic: '🚅',
  },
  {
    no: 314,
    title: 'railway car',
    category: EmojiCategory.Places,
    pic: '🚃',
  },
  {
    no: 315,
    title: 'bus',
    category: EmojiCategory.Places,
    pic: '🚌',
  },
  {
    no: 316,
    title: 'automobile',
    category: EmojiCategory.Places,
    pic: '🚗',
  },
  {
    no: 317,
    title: 'taxi',
    category: EmojiCategory.Places,
    pic: '🚕',
  },
  {
    no: 318,
    title: 'delivery truck',
    category: EmojiCategory.Places,
    pic: '🚚',
  },
  {
    no: 319,
    title: 'police car light',
    category: EmojiCategory.Places,
    pic: '🚨',
  },
  {
    no: 320,
    title: 'police car',
    category: EmojiCategory.Places,
    pic: '🚓',
  },
  {
    no: 321,
    title: 'fire engine',
    category: EmojiCategory.Places,
    pic: '🚒',
  },
  {
    no: 322,
    title: 'ambulance',
    category: EmojiCategory.Places,
    pic: '🚑',
  },
  {
    no: 323,
    title: 'bicycle',
    category: EmojiCategory.Places,
    pic: '🚲',
  },
  {
    no: 324,
    title: 'Japanese symbol for beginner',
    category: EmojiCategory.Places,
    pic: '🔰',
  },
  {
    no: 325,
    title: 'fuel pump',
    category: EmojiCategory.Places,
    pic: '⛽',
  },
  {
    no: 326,
    title: 'red paper lantern',
    category: EmojiCategory.Places,
    pic: '🏮',
  },
  {
    no: 327,
    title: 'slot machine',
    category: EmojiCategory.Places,
    pic: '🎰',
  },
  {
    no: 328,
    title: 'racing car',
    category: EmojiCategory.Places,
    pic: '🏎',
  },
  {
    no: 329,
    title: 'motorcycle',
    category: EmojiCategory.Places,
    pic: '🏍',
  },
  {
    no: 330,
    title: 'small airplane',
    category: EmojiCategory.Places,
    pic: '🛩',
  },
  {
    no: 331,
    title: 'airplane departure',
    category: EmojiCategory.Places,
    pic: '🛫',
  },
  {
    no: 332,
    title: 'airplane arrival',
    category: EmojiCategory.Places,
    pic: '🛬',
  },
  {
    no: 333,
    title: 'satellite',
    category: EmojiCategory.Places,
    pic: '🛰',
  },
  {
    no: 334,
    title: 'motor boat',
    category: EmojiCategory.Places,
    pic: '🛥',
  },
  {
    no: 335,
    title: 'passenger ship',
    category: EmojiCategory.Places,
    pic: '🛳',
  },
  {
    no: 336,
    title: 'SOS button',
    category: EmojiCategory.Symbols,
    pic: '🆘',
  },
  {
    no: 337,
    title: 'no one under eighteen',
    category: EmojiCategory.Symbols,
    pic: '🔞',
  },
  {
    no: 338,
    title: 'no entry',
    category: EmojiCategory.Symbols,
    pic: '⛔',
  },
  {
    no: 339,
    title: 'check mark button',
    category: EmojiCategory.Symbols,
    pic: '✅',
  },
  {
    no: 340,
    title: 'VS button',
    category: EmojiCategory.Symbols,
    pic: '🆚',
  },
  {
    no: 341,
    title: 'chart increasing with yen',
    category: EmojiCategory.Symbols,
    pic: '💹',
  },
  {
    no: 342,
    title: 'heavy dollar sign',
    category: EmojiCategory.Symbols,
    pic: '💲',
  },
  {
    no: 343,
    title: 'currency exchange',
    category: EmojiCategory.Symbols,
    pic: '💱',
  },
  {
    no: 344,
    title: 'cross mark',
    category: EmojiCategory.Symbols,
    pic: '❌',
  },
  {
    no: 345,
    title: 'exclamation mark',
    category: EmojiCategory.Symbols,
    pic: '❗',
  },
  {
    no: 346,
    title: 'question mark',
    category: EmojiCategory.Symbols,
    pic: '❓',
  },
  {
    no: 347,
    title: 'hollow red circle',
    category: EmojiCategory.Symbols,
    pic: '⭕',
  },
  {
    no: 348,
    title: 'hundred points',
    category: EmojiCategory.Symbols,
    pic: '💯',
  },
  {
    no: 349,
    title: 'white flag',
    category: EmojiCategory.Symbols,
    pic: '🏳',
  },
  {
    no: 350,
    title: 'black flag',
    category: EmojiCategory.Symbols,
    pic: '🏴',
  },
];
